apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.label.app }}-svc
  labels:
    app: {{ .Values.label.app }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}
  selector:
    app: {{ .Values.label.app }}
  type: {{ .Values.service.type }}
